### ISSUE TITLE
Ios error

### ISSUE THREAD

**Issue by abdullahalwardi** [shaz-tech/flutter_internet_speed_test#3]
Swift Compiler Error (Xcode): Cannot convert value of type 'Int' to expected argument type 'TimeInterval' (aka 'Double')
/Users/abdullahalwardi/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_internet_speed_test-1.2.0/ios/Classes/SwiftFlutterInternetSpeedTestPlugin.swift:62:107

**Comment by SpaceXM** [comment]
Same error there
