### ISSUE TITLE
Because flutter_internet_speed_test 1.4.0 depends on connectivity_plus ^3.0.3 [...] version solving failed.

### ISSUE THREAD

**Issue by dnkoulouris** [shaz-tech/flutter_internet_speed_test#6]
```
Because flutter_internet_speed_test 1.4.0 depends on connectivity_plus ^3.0.3 and no versions of flutter_internet_speed_test match >1.4.0 <2.0.0, flutter_internet_speed_test ^1.4.0 requires connectivity_plus ^3.0.3.
So, because sign_guide depends on both flutter_internet_speed_test ^1.4.0 and connectivity_plus ^4.0.1, version solving failed.
```
Process finished with exit code 1

Please raise the dependencies.

**Comment by shaz-tech** [comment]
> ```
> Because flutter_internet_speed_test 1.4.0 depends on connectivity_plus ^3.0.3 and no versions of flutter_internet_speed_test match >1.4.0 <2.0.0, flutter_internet_speed_test ^1.4.0 requires connectivity_plus ^3.0.3.
> So, because sign_guide depends on both flutter_internet_speed_test ^1.4.0 and connectivity_plus ^4.0.1, version solving failed.
> ```
> 
> 
>     
>  
>   
> 
> Process finished with exit code 1
> 
> 
> Please raise the dependencies.

I am currently working on it. Thank you for reporting the issue!!
